#!/usr/bin/python

import math

INP = [
    [ 0.34, 0.45 ],
    [ 0.41, 0.38 ],
    [ 0.38, 0.49 ],
    [ 0.32, 0.38 ],
    [ 0.43, 0.39 ],
    [ 0.54, 0.42 ],
    [ 0.54, 0.36 ],
    [ 0.23, 0.58 ],
    [ 0.58, 0.23 ],
    [ 0.88, 0.21 ],
    [ 0.21, 0.88 ],
];



for x in INP:

    _in = x[0] - x[1];

    if x > 0:
        res = (1 / (1+math.exp( -_in )))-0.5;
    else:
        res = (1 / (1+math.exp( _in )))-0.5;


    #if( _in < 0):
    #    res *= -1;
    print( "{:.3f}".format(res) );
    # print( 'in: ', x[0], x[1] ,'out', '('+str(x[0]-x[1])+')' ,res );




